//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorX.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VendorX.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на доступ к контактам запрещен.
        /// </summary>
        internal static string AccesContactError {
            get {
                return ResourceManager.GetString("AccesContactError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принять.
        /// </summary>
        internal static string AccesLabel {
            get {
                return ResourceManager.GetString("AccesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо добавить контакт.
        /// </summary>
        internal static string AddCreditError {
            get {
                return ResourceManager.GetString("AddCreditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        internal static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлено максимальное количество фотографий.
        /// </summary>
        internal static string AddMaxCountPhotoError {
            get {
                return ResourceManager.GetString("AddMaxCountPhotoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поступление товара.
        /// </summary>
        internal static string AdmissionItemLabel {
            get {
                return ResourceManager.GetString("AdmissionItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прием.
        /// </summary>
        internal static string AdmissionLabel {
            get {
                return ResourceManager.GetString("AdmissionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт.
        /// </summary>
        internal static string AkkLabel {
            get {
                return ResourceManager.GetString("AkkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена всего:.
        /// </summary>
        internal static string AllPriceLabel {
            get {
                return ResourceManager.GetString("AllPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Себестоимость всего:.
        /// </summary>
        internal static string AllSebesLabel {
            get {
                return ResourceManager.GetString("AllSebesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аналитика.
        /// </summary>
        internal static string AnaliticLabel {
            get {
                return ResourceManager.GetString("AnaliticLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Архив.
        /// </summary>
        internal static string ArchiveLabel {
            get {
                return ResourceManager.GetString("ArchiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По возрастанию.
        /// </summary>
        internal static string AscendingLabel {
            get {
                return ResourceManager.GetString("AscendingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        internal static string AttentionLabel {
            get {
                return ResourceManager.GetString("AttentionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автор:.
        /// </summary>
        internal static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний чек:.
        /// </summary>
        internal static string AverageCheck {
            get {
                return ResourceManager.GetString("AverageCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний чек.
        /// </summary>
        internal static string AverageCheckLabel {
            get {
                return ResourceManager.GetString("AverageCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среднее кол-во шт:.
        /// </summary>
        internal static string AverageCountOfItems {
            get {
                return ResourceManager.GetString("AverageCountOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среднее кол-во шт.
        /// </summary>
        internal static string AverageCountOfItemsLabel {
            get {
                return ResourceManager.GetString("AverageCountOfItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средняя цена за шт:.
        /// </summary>
        internal static string AveragePriceOfItem {
            get {
                return ResourceManager.GetString("AveragePriceOfItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средняя цена за шт.
        /// </summary>
        internal static string AveragePriceOfItemLabel {
            get {
                return ResourceManager.GetString("AveragePriceOfItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        internal static string BackLabel {
            get {
                return ResourceManager.GetString("BackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шк.
        /// </summary>
        internal static string BarcodeLabel {
            get {
                return ResourceManager.GetString("BarcodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсканируйте штрих код.
        /// </summary>
        internal static string BarcodeScanerLabel {
            get {
                return ResourceManager.GetString("BarcodeScanerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка привязки:.
        /// </summary>
        internal static string BindingError {
            get {
                return ResourceManager.GetString("BindingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка.
        /// </summary>
        internal static string BindingLabel {
            get {
                return ResourceManager.GetString("BindingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для корректной работы приложения, разрешите  доступ к камере.
        /// </summary>
        internal static string CameraExtError {
            get {
                return ResourceManager.GetString("CameraExtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Камера.
        /// </summary>
        internal static string CameraLabel {
            get {
                return ResourceManager.GetString("CameraLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на невозможно добавить.
        /// </summary>
        internal static string CantAddError {
            get {
                return ResourceManager.GetString("CantAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каталог.
        /// </summary>
        internal static string CatalogLabel {
            get {
                return ResourceManager.GetString("CatalogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сдача :.
        /// </summary>
        internal static string ChangeLabel {
            get {
                return ResourceManager.GetString("ChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить.
        /// </summary>
        internal static string ChangeLocationLabel {
            get {
                return ResourceManager.GetString("ChangeLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка смены пароля:.
        /// </summary>
        internal static string ChangePasswordError {
            get {
                return ResourceManager.GetString("ChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во чеков:.
        /// </summary>
        internal static string CheckCount {
            get {
                return ResourceManager.GetString("CheckCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во чеков.
        /// </summary>
        internal static string CheckCountLabel {
            get {
                return ResourceManager.GetString("CheckCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чек.
        /// </summary>
        internal static string CheckLabel {
            get {
                return ResourceManager.GetString("CheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиент.
        /// </summary>
        internal static string ClientLabel {
            get {
                return ResourceManager.GetString("ClientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        internal static string CloseLabel {
            get {
                return ResourceManager.GetString("CloseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код подтверждения.
        /// </summary>
        internal static string CodeConfirmLabel {
            get {
                return ResourceManager.GetString("CodeConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершить.
        /// </summary>
        internal static string CompleteLabel {
            get {
                return ResourceManager.GetString("CompleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код подтверждения для Vendor.
        /// </summary>
        internal static string ConfirmCodeVendorLabel {
            get {
                return ResourceManager.GetString("ConfirmCodeVendorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение адреса электронной почты.
        /// </summary>
        internal static string ConfirmEmailLabel {
            get {
                return ResourceManager.GetString("ConfirmEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить.
        /// </summary>
        internal static string CONFIRMLABEL {
            get {
                return ResourceManager.GetString("CONFIRMLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение номера телефона.
        /// </summary>
        internal static string ConfirmPhoneLabel {
            get {
                return ResourceManager.GetString("ConfirmPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внесенно:.
        /// </summary>
        internal static string ContributedLabel {
            get {
                return ResourceManager.GetString("ContributedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контроль остатков на складе.
        /// </summary>
        internal static string ControlLeftoversStockLabel {
            get {
                return ResourceManager.GetString("ControlLeftoversStockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Себестоимость не может быть больше цены.
        /// </summary>
        internal static string CostError {
            get {
                return ResourceManager.GetString("CostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Себестоимость:.
        /// </summary>
        internal static string CostPrice {
            get {
                return ResourceManager.GetString("CostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Себестоимость.
        /// </summary>
        internal static string CostPriceLabel {
            get {
                return ResourceManager.GetString("CostPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во.
        /// </summary>
        internal static string CountLabel {
            get {
                return ResourceManager.GetString("CountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол..
        /// </summary>
        internal static string CountLabel_ {
            get {
                return ResourceManager.GetString("CountLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание.
        /// </summary>
        internal static string CreateLabel {
            get {
                return ResourceManager.GetString("CreateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валюта магазина.
        /// </summary>
        internal static string CurrencyStoreLabel {
            get {
                return ResourceManager.GetString("CurrencyStoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Темная.
        /// </summary>
        internal static string DarkLabel {
            get {
                return ResourceManager.GetString("DarkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваши данные устарели, сбросьте пароль.
        /// </summary>
        internal static string DataLoginErrorLabel {
            get {
                return ResourceManager.GetString("DataLoginErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить аккаунт .
        /// </summary>
        internal static string DeleteAkkLabel {
            get {
                return ResourceManager.GetString("DeleteAkkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить товар.
        /// </summary>
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При удалении аккаунта все связанные с ним данные удалятся.
        /// </summary>
        internal static string DeleteUserAttention {
            get {
                return ResourceManager.GetString("DeleteUserAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По убыванию.
        /// </summary>
        internal static string DescendingLabel {
            get {
                return ResourceManager.GetString("DescendingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скидка.
        /// </summary>
        internal static string DiscountLabel {
            get {
                return ResourceManager.GetString("DiscountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За период.
        /// </summary>
        internal static string DuringPeriod {
            get {
                return ResourceManager.GetString("DuringPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Долг :.
        /// </summary>
        internal static string DutyLabel {
            get {
                return ResourceManager.GetString("DutyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коректировка.
        /// </summary>
        internal static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный адрес электронной почты.
        /// </summary>
        internal static string EmailUncorrectError {
            get {
                return ResourceManager.GetString("EmailUncorrectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сотрудники.
        /// </summary>
        internal static string EmployersLabel {
            get {
                return ResourceManager.GetString("EmployersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите описание.
        /// </summary>
        internal static string EnterDescriptionLabel {
            get {
                return ResourceManager.GetString("EnterDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите почту.
        /// </summary>
        internal static string EnterEmailLabel {
            get {
                return ResourceManager.GetString("EnterEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка входа.
        /// </summary>
        internal static string EnterError {
            get {
                return ResourceManager.GetString("EnterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        internal static string ENTERLabel {
            get {
                return ResourceManager.GetString("ENTERLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите номер телефона.
        /// </summary>
        internal static string EnterNumberLabel {
            get {
                return ResourceManager.GetString("EnterNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите период отчета.
        /// </summary>
        internal static string EnterPeriodLabel {
            get {
                return ResourceManager.GetString("EnterPeriodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите код подтверждения.
        /// </summary>
        internal static string EnterСonfirmationСode {
            get {
                return ResourceManager.GetString("EnterСonfirmationСode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string ErrorLabel {
            get {
                return ResourceManager.GetString("ErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        internal static string ExitLabel {
            get {
                return ResourceManager.GetString("ExitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните все обязательные поля и повторите попытку.
        /// </summary>
        internal static string FieldsEmptyError {
            get {
                return ResourceManager.GetString("FieldsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтрация.
        /// </summary>
        internal static string FiltrLabel {
            get {
                return ResourceManager.GetString("FiltrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забыли пароль?.
        /// </summary>
        internal static string ForgetPasswordLabel {
            get {
                return ResourceManager.GetString("ForgetPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на из архива.
        /// </summary>
        internal static string FromArchiveLabel {
            get {
                return ResourceManager.GetString("FromArchiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Галерия.
        /// </summary>
        internal static string GaleryLabel {
            get {
                return ResourceManager.GetString("GaleryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По номеру контакта.
        /// </summary>
        internal static string GroupContactLabel {
            get {
                return ResourceManager.GetString("GroupContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По дате создания.
        /// </summary>
        internal static string GroupDateLabel {
            get {
                return ResourceManager.GetString("GroupDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группировка.
        /// </summary>
        internal static string GroupLabel {
            get {
                return ResourceManager.GetString("GroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По имени контакта.
        /// </summary>
        internal static string GroupNameContactLabel {
            get {
                return ResourceManager.GetString("GroupNameContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пригласил вас в.
        /// </summary>
        internal static string HasInviteInLabel {
            get {
                return ResourceManager.GetString("HasInviteInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на находится в архиве.
        /// </summary>
        internal static string InArchiveError {
            get {
                return ResourceManager.GetString("InArchiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на в архив.
        /// </summary>
        internal static string InArchiveLabel {
            get {
                return ResourceManager.GetString("InArchiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В корзине : .
        /// </summary>
        internal static string InBasketLabel {
            get {
                return ResourceManager.GetString("InBasketLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К оплате:.
        /// </summary>
        internal static string InPayLabel {
            get {
                return ResourceManager.GetString("InPayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На складе:.
        /// </summary>
        internal static string InStock {
            get {
                return ResourceManager.GetString("InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На складе.
        /// </summary>
        internal static string InStockLabel {
            get {
                return ResourceManager.GetString("InStockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приглашение.
        /// </summary>
        internal static string InvitationLabel {
            get {
                return ResourceManager.GetString("InvitationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приглашения.
        /// </summary>
        internal static string InvitationsLabel {
            get {
                return ResourceManager.GetString("InvitationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пригласить по номеру телефону.
        /// </summary>
        internal static string InviteByPhoneNumberLabel {
            get {
                return ResourceManager.GetString("InviteByPhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пригласить.
        /// </summary>
        internal static string InviteLabel {
            get {
                return ResourceManager.GetString("InviteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на будет удален, это действие необратимо. Продолжить?.
        /// </summary>
        internal static string ItemDeleteAttention {
            get {
                return ResourceManager.GetString("ItemDeleteAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KGS.
        /// </summary>
        internal static string KgSom {
            get {
                return ResourceManager.GetString("KgSom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KZT.
        /// </summary>
        internal static string KzTengeLabel {
            get {
                return ResourceManager.GetString("KzTengeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светлая.
        /// </summary>
        internal static string LightLabel {
            get {
                return ResourceManager.GetString("LightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязать почту.
        /// </summary>
        internal static string LinkMailLabel {
            get {
                return ResourceManager.GetString("LinkMailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязать телефон.
        /// </summary>
        internal static string LinkPhoneLabel {
            get {
                return ResourceManager.GetString("LinkPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный логин или пароль.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Убыток:.
        /// </summary>
        internal static string Loss {
            get {
                return ResourceManager.GetString("Loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Убыток.
        /// </summary>
        internal static string LossLabel {
            get {
                return ResourceManager.GetString("LossLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер.
        /// </summary>
        internal static string ManagerLabel {
            get {
                return ResourceManager.GetString("ManagerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наценка.
        /// </summary>
        internal static string MarkupLabel {
            get {
                return ResourceManager.GetString("MarkupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний чек:.
        /// </summary>
        internal static string MediumCheckLabel {
            get {
                return ResourceManager.GetString("MediumCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средняя цена за единицу:.
        /// </summary>
        internal static string MediumPriceEdLabel {
            get {
                return ResourceManager.GetString("MediumPriceEdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название обязательно для заполнения.
        /// </summary>
        internal static string NameError {
            get {
                return ResourceManager.GetString("NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        internal static string NamESLabel {
            get {
                return ResourceManager.GetString("NamESLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите почту или номер телефона.
        /// </summary>
        internal static string NameUserLabel {
            get {
                return ResourceManager.GetString("NameUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На указанный адрес электронной почты был отправлен новый код подтверждения..
        /// </summary>
        internal static string NewCodeSendError {
            get {
                return ResourceManager.GetString("NewCodeSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На указанный номер телефона был отправлен новый код подтверждения..
        /// </summary>
        internal static string NewPhoneCodeSend {
            get {
                return ResourceManager.GetString("NewPhoneCodeSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отклонить.
        /// </summary>
        internal static string NoAccesLabel {
            get {
                return ResourceManager.GetString("NoAccesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на в списке нет товара с штрихкодом.
        /// </summary>
        internal static string NoBarcodeInListError {
            get {
                return ResourceManager.GetString("NoBarcodeInListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на нет в достаточном количествe.
        /// </summary>
        internal static string NoCountError {
            get {
                return ResourceManager.GetString("NoCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В этом магазине нет товаров.
        /// </summary>
        internal static string NoItemsInStore {
            get {
                return ResourceManager.GetString("NoItemsInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        internal static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не сортировать.
        /// </summary>
        internal static string NoSortLabel {
            get {
                return ResourceManager.GetString("NoSortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введенный вами код подтверждения неверный или устарел. Убедитесь, что вы вводите последний выданный вам код подтверждения, и повторите попытку..
        /// </summary>
        internal static string NotCorrectCodeError {
            get {
                return ResourceManager.GetString("NotCorrectCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание :.
        /// </summary>
        internal static string NoteLabel {
            get {
                return ResourceManager.GetString("NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомления.
        /// </summary>
        internal static string NotificationsLabels {
            get {
                return ResourceManager.GetString("NotificationsLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на нет в достаточном  количестве..
        /// </summary>
        internal static string NotInStockLabel {
            get {
                return ResourceManager.GetString("NotInStockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сменить пароль. Проверьте правильность введенных данных и убедитесь, что вы подключены к интернету..
        /// </summary>
        internal static string NotSuccesRestorePwdError {
            get {
                return ResourceManager.GetString("NotSuccesRestorePwdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер квитанции.
        /// </summary>
        internal static string NumberCheckLabel {
            get {
                return ResourceManager.GetString("NumberCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только актуальные.
        /// </summary>
        internal static string OnlyActualLabel {
            get {
                return ResourceManager.GetString("OnlyActualLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только поступление.
        /// </summary>
        internal static string OnlyAdmissionLabel {
            get {
                return ResourceManager.GetString("OnlyAdmissionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только архивные.
        /// </summary>
        internal static string OnlyArchiveLabel {
            get {
                return ResourceManager.GetString("OnlyArchiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только оплаченные.
        /// </summary>
        internal static string OnlyPaidLabel {
            get {
                return ResourceManager.GetString("OnlyPaidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на доступен только для чтения.
        /// </summary>
        internal static string OnlyReaderError {
            get {
                return ResourceManager.GetString("OnlyReaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только возвраты.
        /// </summary>
        internal static string OnlyReturnLabel {
            get {
                return ResourceManager.GetString("OnlyReturnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только продажи.
        /// </summary>
        internal static string OnlySalesLabel {
            get {
                return ResourceManager.GetString("OnlySalesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только не оплаченные.
        /// </summary>
        internal static string OnlyUnPaidLabel {
            get {
                return ResourceManager.GetString("OnlyUnPaidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на на должность :.
        /// </summary>
        internal static string OnRoleLabel {
            get {
                return ResourceManager.GetString("OnRoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция.
        /// </summary>
        internal static string OperationLabel {
            get {
                return ResourceManager.GetString("OperationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ.
        /// </summary>
        internal static string OrderLabel {
            get {
                return ResourceManager.GetString("OrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доп. скидка :.
        /// </summary>
        internal static string OverDiscountLabel {
            get {
                return ResourceManager.GetString("OverDiscountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Владелец.
        /// </summary>
        internal static string OwnerLabel {
            get {
                return ResourceManager.GetString("OwnerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платежи.
        /// </summary>
        internal static string PaymentsLabel {
            get {
                return ResourceManager.GetString("PaymentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период:.
        /// </summary>
        internal static string PeriodLabel {
            get {
                return ResourceManager.GetString("PeriodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по.
        /// </summary>
        internal static string Po {
            get {
                return ResourceManager.GetString("Po", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена не может быть меньше или равна нулю.
        /// </summary>
        internal static string PriceError {
            get {
                return ResourceManager.GetString("PriceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        internal static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прайс-лист.
        /// </summary>
        internal static string PriceListLabel {
            get {
                return ResourceManager.GetString("PriceListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не получилось войти в профиль.
        /// </summary>
        internal static string ProfileEnterError {
            get {
                return ResourceManager.GetString("ProfileEnterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибыль:.
        /// </summary>
        internal static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рентабельность:.
        /// </summary>
        internal static string ProfitabilityLabel {
            get {
                return ResourceManager.GetString("ProfitabilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибыль.
        /// </summary>
        internal static string ProfitLabel {
            get {
                return ResourceManager.GetString("ProfitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль изменен.
        /// </summary>
        internal static string PwdChangeLabel {
            get {
                return ResourceManager.GetString("PwdChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слишком короткий пароль. Пароль должен содержать не менее 8 символов и хотя бы одну заглавную букву..
        /// </summary>
        internal static string PwdLess8Error {
            get {
                return ResourceManager.GetString("PwdLess8Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введенные пароли не совпадают. Убедитесь, что вы правильно ввели пароль и повторите попытку..
        /// </summary>
        internal static string PwdNotEqualError {
            get {
                return ResourceManager.GetString("PwdNotEqualError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возвраты:.
        /// </summary>
        internal static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возвраты.
        /// </summary>
        internal static string RefundLabel {
            get {
                return ResourceManager.GetString("RefundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка регистрации:.
        /// </summary>
        internal static string RegisterError {
            get {
                return ResourceManager.GetString("RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        internal static string RegistrationLabel {
            get {
                return ResourceManager.GetString("RegistrationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связанные транзакции.
        /// </summary>
        internal static string RelatedTransactionLabel {
            get {
                return ResourceManager.GetString("RelatedTransactionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить код повторно.
        /// </summary>
        internal static string RepeatCodeLabel {
            get {
                return ResourceManager.GetString("RepeatCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите пароль.
        /// </summary>
        internal static string RepeatPasswordLabel {
            get {
                return ResourceManager.GetString("RepeatPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторная отправка кода будет доступна через .
        /// </summary>
        internal static string RepeatSendCodeError {
            get {
                return ResourceManager.GetString("RepeatSendCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коммерческий отчет.
        /// </summary>
        internal static string ReportComercialLabel {
            get {
                return ResourceManager.GetString("ReportComercialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет по Возвратам.
        /// </summary>
        internal static string ReportRefundsLabel {
            get {
                return ResourceManager.GetString("ReportRefundsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет по продажам.
        /// </summary>
        internal static string ReportSalesLabel {
            get {
                return ResourceManager.GetString("ReportSalesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет по складу.
        /// </summary>
        internal static string ReportStockLabel {
            get {
                return ResourceManager.GetString("ReportStockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cбросить пароль по номеру телефону.
        /// </summary>
        internal static string ResetPwdByPhoneLabel {
            get {
                return ResourceManager.GetString("ResetPwdByPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить пароль.
        /// </summary>
        internal static string ResetPwdLabel {
            get {
                return ResourceManager.GetString("ResetPwdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка смены пароля:.
        /// </summary>
        internal static string RestorePwdError {
            get {
                return ResourceManager.GetString("RestorePwdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление пароля.
        /// </summary>
        internal static string RestorePwdLabel {
            get {
                return ResourceManager.GetString("RestorePwdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возврат.
        /// </summary>
        internal static string ReturnLabel {
            get {
                return ResourceManager.GetString("ReturnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выручка:.
        /// </summary>
        internal static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выручка.
        /// </summary>
        internal static string RevenueLabel {
            get {
                return ResourceManager.GetString("RevenueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RUB.
        /// </summary>
        internal static string RuRubLabel {
            get {
                return ResourceManager.GetString("RuRubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на с.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продажа.
        /// </summary>
        internal static string SaleLabel {
            get {
                return ResourceManager.GetString("SaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продажи:.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продажи.
        /// </summary>
        internal static string SalesLabel {
            get {
                return ResourceManager.GetString("SalesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продавец.
        /// </summary>
        internal static string SalesmanLabel {
            get {
                return ResourceManager.GetString("SalesmanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Себес.
        /// </summary>
        internal static string SebesLabel {
            get {
                return ResourceManager.GetString("SebesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на секунд..
        /// </summary>
        internal static string SecondLabel {
            get {
                return ResourceManager.GetString("SecondLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбран.
        /// </summary>
        internal static string SelectLabel {
            get {
                return ResourceManager.GetString("SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить код подтверждения.
        /// </summary>
        internal static string SendCodeConfirmLabel {
            get {
                return ResourceManager.GetString("SendCodeConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На указанный адрес электронной почты было отправлено письмо с кодом подтверждения для вашего аккаунта..
        /// </summary>
        internal static string SendCodeEmailLabel {
            get {
                return ResourceManager.GetString("SendCodeEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        internal static string SendLabel {
            get {
                return ResourceManager.GetString("SendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На указанный номер телефона было отправлено SMS с кодом подтверждения для вашего аккаунта..
        /// </summary>
        internal static string SendSMSCodeLabel {
            get {
                return ResourceManager.GetString("SendSMSCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string SettingLabel {
            get {
                return ResourceManager.GetString("SettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображать все.
        /// </summary>
        internal static string ShowAllLabel {
            get {
                return ResourceManager.GetString("ShowAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать отмененные.
        /// </summary>
        internal static string ShowCancelOrder {
            get {
                return ResourceManager.GetString("ShowCancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать доставленные.
        /// </summary>
        internal static string ShowDeliveredOrder {
            get {
                return ResourceManager.GetString("ShowDeliveredOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать в процессе.
        /// </summary>
        internal static string ShowProccesOrder {
            get {
                return ResourceManager.GetString("ShowProccesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать отправленные.
        /// </summary>
        internal static string ShowShippedOrder {
            get {
                return ResourceManager.GetString("ShowShippedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на шт.
        /// </summary>
        internal static string ShtLabel {
            get {
                return ResourceManager.GetString("ShtLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка.
        /// </summary>
        internal static string SortLabel {
            get {
                return ResourceManager.GetString("SortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звуковые эффекты.
        /// </summary>
        internal static string SoundEffects {
            get {
                return ResourceManager.GetString("SoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звук при сканировании.
        /// </summary>
        internal static string SoundScanning {
            get {
                return ResourceManager.GetString("SoundScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От меньшего кол-ва.
        /// </summary>
        internal static string StartCountLessLabel {
            get {
                return ResourceManager.GetString("StartCountLessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От большего кол-ва.
        /// </summary>
        internal static string StartCountMoreLabel {
            get {
                return ResourceManager.GetString("StartCountMoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала дешевые.
        /// </summary>
        internal static string StartLessLabel {
            get {
                return ResourceManager.GetString("StartLessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала новые.
        /// </summary>
        internal static string StartNewLabel {
            get {
                return ResourceManager.GetString("StartNewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала дорогие.
        /// </summary>
        internal static string StartRichLabel {
            get {
                return ResourceManager.GetString("StartRichLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Склад.
        /// </summary>
        internal static string StockLabel {
            get {
                return ResourceManager.GetString("StockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация завершина.
        /// </summary>
        internal static string SuccesRegisterLabel {
            get {
                return ResourceManager.GetString("SuccesRegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль изменен.
        /// </summary>
        internal static string SuccesRestorePwdLabel {
            get {
                return ResourceManager.GetString("SuccesRestorePwdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не удалось завершить регистрацию. Пожалуйста, проверьте правильность введенных данных и убедитесь, что вы подключены к интернету..
        /// </summary>
        internal static string SuccessRegisterError {
            get {
                return ResourceManager.GetString("SuccessRegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма:.
        /// </summary>
        internal static string SummLabel {
            get {
                return ResourceManager.GetString("SummLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете переключать магазины без доступа к интернету.
        /// </summary>
        internal static string SwitchShopError {
            get {
                return ResourceManager.GetString("SwitchShopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Системная.
        /// </summary>
        internal static string SystemLabel {
            get {
                return ResourceManager.GetString("SystemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #Теги.
        /// </summary>
        internal static string TagsLabel {
            get {
                return ResourceManager.GetString("TagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спасибо за покупку!.
        /// </summary>
        internal static string ThanksPayLabel {
            get {
                return ResourceManager.GetString("ThanksPayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема.
        /// </summary>
        internal static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого:.
        /// </summary>
        internal static string TotalLabel {
            get {
                return ResourceManager.GetString("TotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транзакции.
        /// </summary>
        internal static string TransactionLabel {
            get {
                return ResourceManager.GetString("TransactionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер квитанции:.
        /// </summary>
        internal static string TransactionNumberLabel {
            get {
                return ResourceManager.GetString("TransactionNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что-то пошло не так. пожалуйста попробуйте позже.
        /// </summary>
        internal static string TryLaterLabel {
            get {
                return ResourceManager.GetString("TryLaterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USD .
        /// </summary>
        internal static string UsDollarLabel {
            get {
                return ResourceManager.GetString("UsDollarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь уже зарегистрирован.
        /// </summary>
        internal static string UserAlreadyExist {
            get {
                return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь уже был приглашен или числиться в магазине.
        /// </summary>
        internal static string UserInvitedInStoreError {
            get {
                return ResourceManager.GetString("UserInvitedInStoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UZS.
        /// </summary>
        internal static string UzSumLabel {
            get {
                return ResourceManager.GetString("UzSumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверьте правильность введенных данных и убедитесь, что вы подключены к интернету..
        /// </summary>
        internal static string ValidityError {
            get {
                return ResourceManager.GetString("ValidityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вибрация при сканировании.
        /// </summary>
        internal static string VibrationScanning {
            get {
                return ResourceManager.GetString("VibrationScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость.
        /// </summary>
        internal static string WorthLabel {
            get {
                return ResourceManager.GetString("WorthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный адрес электронной почты.
        /// </summary>
        internal static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный номер телефона.
        /// </summary>
        internal static string WrongNumber {
            get {
                return ResourceManager.GetString("WrongNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        internal static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас недостаточно прав.
        /// </summary>
        internal static string YouHaveNotAccesError {
            get {
                return ResourceManager.GetString("YouHaveNotAccesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы.
        /// </summary>
        internal static string YouLabel {
            get {
                return ResourceManager.GetString("YouLabel", resourceCulture);
            }
        }
    }
}
